### ISSUE TITLE
Visualization of zone-edge phonons

### ISSUE THREAD

**Issue by JJefff** [materialscloud-org/tools-phonon-dispersion#5]
In zone-edge phonon modes, the movements of neighbouring unit cells should be out of phase. In other words, every other unit cell should be in phase. This does not seem to be rendered correctly by the visualiser.

For example, using the example data for C2 (graphene) and selecting an acoustic phonon mode at the z one edge (M-point), every 5th unit cell appears to be in phase instead of every 2nd unit cell (see below).

![visualisation](https://user-images.githubusercontent.com/20703111/96269549-cc47cc80-0fca-11eb-9fcf-2076699b3bf1.png)
![dispersion](https://user-images.githubusercontent.com/20703111/96269532-c520be80-0fca-11eb-9299-57da5750d552.png)

**Comment by giovannipizzi** [comment]
Thanks for the report!
We'll need to check, It might be a unit conversion issue.
Could you upload your input files, please, so we can check?
Mentioning @asle85 and @vgranata to follow up on this

**Comment by giovannipizzi** [comment]
Just a comment that @elsapassaro just put the new version with this (and a few more) fixes in production
